In [2]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.9.2                |   py37haa95532_0         2.9 MB
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following packages will be UPDATED:

  conda                                       4.7.12-py37_0 --> 4.9.2-py37haa95532_0




conda-4.9.2          | 2.9 MB    |            |   0% 
conda-4.9.2          | 2.9 MB    |            |   1% 
conda-4.9.2          | 2.9 MB    | 4          |   5% 
conda-4.9.2          | 2.9 MB    | #          |  10% 
conda-4.9.2          | 2.9 MB    | ##7        |  28% 
conda-4.9.2          | 2.9 MB    | #####7     |  57% 
conda-4.9.2          | 2.9 MB    | #######6   |  77% 
co

In [3]:
import numpy as np

In [4]:
np.__version__

'1.16.5'

In [16]:
a = np.arange(0, 21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [17]:
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [18]:
a[3::3]

array([ 3,  6,  9, 12, 15, 18])