In [91]:
import copy
import numpy as np

In [92]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])
math_score

array([60., 85., 60., 68., nan, 60.])

In [93]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

In [94]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

In [95]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?

In [96]:
#english
english_average = np.mean(english_score)
english_max = np.amax(english_score)
english_min = np.amin(english_score)
english_standard = np.std(english_score)
print("英文平均:", english_average, "英文最大值:", english_max, "英文最小值:", english_min, "英文標準差:",english_standard)
#math
math_average = np.nanmean(math_score)
math_max = np.nanmax(math_score)
math_min = np.nanmin(math_score)
math_standard = np.nanstd(math_score)
print("數學平均:", math_average, "數學最大值:", math_max, "數學最小值:", math_min, "數學標準差:",math_standard)
#chinese
chinese_average = np.mean(chinese_score)
chinese_max = np.amax(chinese_score)
chinese_min = np.amin(chinese_score)
chinese_standard = np.std(chinese_score)
print("國文平均:", chinese_average, "國文最大值:", chinese_max, "國文最小值:", chinese_min, "國文標準差:",chinese_standard)

英文平均: 67.16666666666667 英文最大值: 89 英文最小值: 48 英文標準差: 13.433995020924426
數學平均: 66.6 數學最大值: 85.0 數學最小值: 60.0 數學標準差: 9.707728879609279
國文平均: 75.33333333333333 國文最大值: 90 國文最小值: 65 國文標準差: 8.825468196582484


In [97]:
after_math_score = copy.copy(math_score)
after_math_score[4] = 55
after_math_average = np.nanmean(after_math_score)
after_math_max = np.nanmax(after_math_score)
after_math_min = np.nanmin(after_math_score)
after_math_standard = np.nanstd(math_score)
print("修改後數學平均:", after_math_average, "數學最大值:", after_math_max, "數學最小值:", after_math_min, "數學標準差:",after_math_standard)

修改後數學平均: 64.66666666666667 數學最大值: 85.0 數學最小值: 55.0 數學標準差: 9.707728879609279


In [104]:
english_corr = np.corrcoef([65,90,82,72,66,77], [55,89,76,65,48,70])
math_corr = np.corrcoef([65,90,82,72,66,77], [60,85,60,68,55,60])
print(english_corr)
print(math_corr)

[[1.         0.97792828]
 [0.97792828 1.        ]]
[[1.         0.74056803]
 [0.74056803 1.        ]]
