In [29]:
import numpy as np

In [30]:
#1. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

In [31]:
with open('new_array.npz', 'wb'):
    np.savez('new_array.npz', array1=array1,array2=array2)

In [32]:
npzfile = np.load('new_array.npz')
npzfile.files

['array1', 'array2']

In [33]:
print(npzfile['array1'])
print(npzfile['array2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [34]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

In [35]:
array3 = np.array([[4, 5, 6],[1, 2, 3]])
with open('new_array.npz', 'wb'):
    np.savez('second_array.npz',array1=npzfile['array1'], array2=npzfile['array2'], array3=array3)

In [36]:
sec_npzfile = np.load('second_array.npz')
sec_npzfile.files

['array1', 'array2', 'array3']

In [37]:
print(sec_npzfile['array1'])
print(sec_npzfile['array2'])
print(sec_npzfile['array3'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
