In [1]:
import numpy as np

In [2]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

In [3]:
np.linalg.inv(array1)

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [4]:
np.linalg.inv(array1)@array1

array([[1., 0.],
       [0., 1.]])

In [5]:
#2. 運用上列array計算特徵值、特徵向量?

In [6]:
w, v = np.linalg.eig(array1)

In [7]:
w

array([13.,  2.])

In [8]:
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [9]:
#3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)

In [10]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [11]:
s

array([13.94721714,  1.86417116])

In [12]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])